version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      rust-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    commit-message:
      prefix: deps
    groups:
      root-container-images:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/packaging/postgres-extension"
    schedule:
      interval: weekly
      day: monday
      time: "09:45"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    commit-message:
      prefix: deps
    groups:
      extension-container-images:
        patterns:
          - "*"
