use crate::{push_html_escaped, push_key_value, push_metric_card, ChaosRunSummary};

pub(crate) fn push_chaos_report_overview(html: &mut String, summary: &ChaosRunSummary) {
    html.push_str("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
    html.push_str("<title>Trellara Correctness Report</title>");
    html.push_str("<style>");
    html.push_str("body{margin:0;font-family:Inter,Arial,sans-serif;background:#f6f7f9;color:#111827}main{max-width:1120px;margin:0 auto;padding:40px 20px 64px}header{border-bottom:1px solid #d8dee8;padding-bottom:24px;margin-bottom:28px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#546179}h1{font-size:40px;line-height:1.05;margin:10px 0 12px}p{color:#4b5563;line-height:1.55}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:24px 0}.metric,.panel{background:white;border:1px solid #d8dee8;border-radius:8px;padding:16px}.metric strong{display:block;font-size:28px;color:#111827}.metric span{font-size:13px;color:#546179}.status{display:inline-flex;align-items:center;border-radius:999px;padding:4px 10px;font-size:12px;font-weight:700}.ok{background:#e8f7ef;color:#116038}.risk{background:#fff4dc;color:#7a4b00}table{width:100%;border-collapse:collapse;background:white;border:1px solid #d8dee8;border-radius:8px;overflow:hidden}th,td{text-align:left;border-bottom:1px solid #e5eaf1;padding:10px 12px;font-size:13px;vertical-align:top}th{background:#edf1f6;color:#374151}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}section{margin-top:30px}@media(max-width:760px){.grid{grid-template-columns:1fr 1fr}h1{font-size:32px}}");
    html.push_str("</style></head><body><main>");
    html.push_str("<header><div class=\"eyebrow\">Trellara correctness report</div>");
    html.push_str("<h1>Deterministic failure proof for Postgres CDC</h1>");
    html.push_str("<p>This static report is generated from Trellara's replayable simulator and curated chaos matrix. It is designed for CI publishing so buyers can inspect the failure boundaries instead of trusting a reliability claim.</p>");
    html.push_str("</header>");

    html.push_str("<div class=\"grid\">");
    push_metric_card(
        html,
        "Overall",
        if summary.passed { "PASS" } else { "AT RISK" },
    );
    push_metric_card(html, "Simulations", &summary.simulation_count.to_string());
    push_metric_card(html, "Chaos Scenarios", &summary.scenario_count.to_string());
    push_metric_card(html, "Seed", &summary.deterministic_seed.to_string());
    html.push_str("</div>");

    html.push_str("<section class=\"panel\"><h2>CI Contract</h2><p>Verification command: <code>");
    push_html_escaped(html, &summary.verification_command);
    html.push_str("</code></p><p>Mode: <code>");
    push_html_escaped(html, &summary.mode);
    html.push_str("</code></p></section>");

    html.push_str("<section class=\"panel\"><h2>Report Identity</h2>");
    push_key_value(html, "Artifact", &summary.metadata.artifact);
    push_key_value(html, "Report version", &summary.metadata.report_version);
    push_key_value(html, "Package version", &summary.metadata.package_version);
    push_key_value(html, "Source revision", &summary.metadata.source_revision);
    push_key_value(
        html,
        "Source repository",
        &summary.metadata.source_repository,
    );
    push_key_value(html, "Workflow run", &summary.metadata.workflow_run_url);
    push_key_value(html, "Generated by", &summary.metadata.generated_by);
    push_key_value(html, "Freshness check", &summary.metadata.freshness_check);
    html.push_str("</section>");

    html.push_str("<section class=\"panel\"><h2>Performance Envelope</h2>");
    push_key_value(
        html,
        "Quickstart target",
        &format!(
            "{} minute estimate within {} minute budget",
            summary.performance_envelope.quickstart_estimated_minutes,
            summary.performance_envelope.quickstart_time_budget_minutes
        ),
    );
    push_key_value(
        html,
        "Default local relay/apply bound",
        &format!(
            "{} transactions / {} messages",
            summary.performance_envelope.default_relay_max_transactions,
            summary.performance_envelope.default_apply_max_messages
        ),
    );
    push_key_value(
        html,
        "Stream spill threshold",
        &format!(
            "{} changes",
            summary.performance_envelope.stream_spill_threshold_changes
        ),
    );
    push_key_value(
        html,
        "Stream spill location",
        &summary.performance_envelope.stream_spill_location,
    );
    push_key_value(
        html,
        "Large transaction mode",
        &summary.performance_envelope.bounded_large_transaction_mode,
    );
    push_key_value(
        html,
        "Local durability acknowledgement",
        &summary.performance_envelope.local_transport_ack,
    );
    push_key_value(
        html,
        "Local indexed replay",
        &summary.performance_envelope.local_transport_replay,
    );
    html.push_str("</section>");

    html.push_str("<section class=\"panel\"><h2>Enterprise Proof Review Path</h2>");
    html.push_str("<p>This report is the public failure-evidence leg of the same proof chain exported by <code>trellara pilot-package</code>. Reviewers should connect the deterministic failure matrix to live source, boundary, convergence, and recovery artifacts before approving a production pilot.</p>");
    html.push_str("<table><thead><tr><th>Review question</th><th>Proof surface</th><th>Enterprise gate</th></tr></thead><tbody>");
    for gate in &summary.enterprise_review_gates {
        html.push_str("<tr><td>");
        push_html_escaped(html, &gate.question);
        html.push_str("</td><td><code>");
        push_html_escaped(html, &gate.proof_surface);
        html.push_str("</code></td><td>");
        push_html_escaped(html, &gate.gate);
        html.push_str("</td></tr>");
    }
    html.push_str("</tbody></table></section>");
}
