use crate::*;

pub async fn execute(cli: Cli) -> Result<String> {
    match cli.command {
        Command::Version => Ok(format!("trellara {}", env!("CARGO_PKG_VERSION"))),
        Command::Check(args) | Command::SourceSafety(args) => source_safety_command(args).await,
        Command::Init(args) => init_flow_config(&args),
        Command::Quickstart(args) => quickstart_command(args),
        Command::MvpCheck(args) => mvp_check_command(args),
        Command::Evaluate(args) => evaluate_command(args),
        Command::Consistency(args) => consistency_command(args),
        Command::Performance(args) => performance_command(args),
        Command::IdentityAudit(args) => identity_audit_command(args),
        Command::EvidenceRegistry(args) => evidence_registry_command(args),
        Command::Semantics(args) => semantics_command(args),
        Command::Demo(args) | Command::Run(args) => run_command(args).await,
        Command::Fleet { command } => execute_fleet_command(command),
        Command::Dev { command } => execute_dev_command(command),
        Command::Config { command } => execute_configuration_command(command),
        Command::Flow { command } => execute_flow_command(command).await,
        Command::Validate(args) => flow_validate_command(args),
        Command::Status(args) => status_command(args).await,
        Command::Contract { command } => execute_contract_command(command).await,
        Command::ContractTest(args) => contract_test_command(args).await,
        Command::Schema { command } => execute_schema_command(command).await,
        Command::SchemaDiscover(args) => schema_discover_command(args).await,
        Command::Lake { command } => execute_lake_command(command),
        Command::Stream { command } => execute_stream_command(command),
        Command::Native { command } => execute_native_command(command),
        Command::Chaos { command } => execute_chaos_command(command),
        Command::Explain(args) => explain_command(args),
        Command::Preflight(args) => preflight_command(args).await,
        Command::Bootstrap(args) => bootstrap_command(args).await,
        Command::Relay(args) => relay_command(args).await,
        Command::ApplySchema(args) => apply_schema_command(args).await,
        Command::Apply(args) => apply_command(args).await,
        Command::Snapshot(args) => snapshot_command(args).await,
        Command::Verify(args) => verify_command(args).await,
        Command::Reseed(args) => reseed_command(args).await,
        Command::Report(args) => correctness_report_command(args).await,
        Command::Alerts(args) => alerts_command(args).await,
        Command::Dashboard(args) => dashboard_command(args).await,
        Command::Metrics(args) => metrics_command(args).await,
        Command::Diagnostics(args) => diagnostics_command(args).await,
        Command::Repair { command } => execute_repair_command(command).await,
        Command::RepairPlan(args) => repair_plan_command(args).await,
        Command::Pilot { command } => execute_pilot_command(command),
        Command::PilotGuide(args) => pilot_guide_command(args),
        Command::PilotScorecard(args) => pilot_scorecard_command(args),
        Command::PilotEvidence(args) => pilot_evidence_command(args),
        Command::PilotEvidenceCheck(args) => pilot_evidence_check_command(args),
        Command::PilotEvidenceTemplate(args) => pilot_evidence_template_command(args),
        Command::PilotPackage(args) => pilot_package_command(args),
        Command::InspectTransaction(args) => inspect_transaction_command(args),
        Command::PartitionLocal(args) => partition_local_command(args),
        Command::PartitionWatermarks(args) => partition_watermarks_command(args).await,
        Command::PartitionRebalancePlan(args) => partition_rebalance_plan_command(args).await,
        Command::Quarantine { command } => execute_quarantine_command(command).await,
    }
}
