#[path = "config.rs"]
pub(crate) mod config;
#[path = "config_engine_conversions.rs"]
pub(crate) mod config_engine_conversions;
#[path = "config_explain.rs"]
pub(crate) mod config_explain;
#[path = "config_migration.rs"]
pub(crate) mod config_migration;
#[path = "config_partition.rs"]
pub(crate) mod config_partition;
#[path = "config_redaction.rs"]
pub(crate) mod config_redaction;
#[path = "config_relay_mode.rs"]
pub(crate) mod config_relay_mode;
#[path = "config_secret.rs"]
pub(crate) mod config_secret;
#[path = "config_source.rs"]
pub(crate) mod config_source;
#[path = "config_stream.rs"]
pub(crate) mod config_stream;
#[path = "config_stream_conversions.rs"]
pub(crate) mod config_stream_conversions;
#[path = "config_table.rs"]
pub(crate) mod config_table;
#[path = "config_topics.rs"]
pub(crate) mod config_topics;
#[path = "config_types.rs"]
pub(crate) mod config_types;
#[path = "config_validate.rs"]
pub(crate) mod config_validate;
#[path = "consistency.rs"]
pub(crate) mod consistency;
#[path = "consistency_builder.rs"]
pub(crate) mod consistency_builder;
#[path = "consistency_clauses.rs"]
pub(crate) mod consistency_clauses;
#[path = "consistency_invariants.rs"]
pub(crate) mod consistency_invariants;
#[path = "consistency_partition.rs"]
pub(crate) mod consistency_partition;
#[path = "consistency_render.rs"]
pub(crate) mod consistency_render;
#[path = "consumer.rs"]
pub(crate) mod consumer;
#[path = "consumer_partition_local.rs"]
pub(crate) mod consumer_partition_local;
#[path = "consumer_semantics.rs"]
pub(crate) mod consumer_semantics;
#[path = "consumer_semantics_exact.rs"]
pub(crate) mod consumer_semantics_exact;
#[path = "consumer_semantics_partition_local.rs"]
pub(crate) mod consumer_semantics_partition_local;
#[path = "consumer_stream.rs"]
pub(crate) mod consumer_stream;
#[path = "contract_apply.rs"]
pub(crate) mod contract_apply;
#[path = "contract_boundary_checks.rs"]
pub(crate) mod contract_boundary_checks;
#[path = "contract_discovery.rs"]
pub(crate) mod contract_discovery;
#[path = "contract_partition_checks.rs"]
pub(crate) mod contract_partition_checks;
#[path = "contract_preflight_summary.rs"]
pub(crate) mod contract_preflight_summary;
#[path = "contract_recovery.rs"]
pub(crate) mod contract_recovery;
#[path = "contract_relation_checks.rs"]
pub(crate) mod contract_relation_checks;
#[path = "contract_relation_identity.rs"]
pub(crate) mod contract_relation_identity;
#[path = "contract_relation_metadata.rs"]
pub(crate) mod contract_relation_metadata;
#[path = "contract_relation_toast.rs"]
pub(crate) mod contract_relation_toast;
#[path = "contract_target_apply.rs"]
pub(crate) mod contract_target_apply;
#[path = "contract_type_compat.rs"]
pub(crate) mod contract_type_compat;
#[path = "contract_types.rs"]
pub(crate) mod contract_types;
#[path = "contracts.rs"]
pub(crate) mod contracts;
