#[path = "ddl.rs"]
pub(crate) mod ddl;
#[path = "ddl_apply_digest.rs"]
pub(crate) mod ddl_apply_digest;
#[path = "ddl_apply_plan.rs"]
pub(crate) mod ddl_apply_plan;
#[path = "ddl_apply_render.rs"]
pub(crate) mod ddl_apply_render;
#[path = "ddl_barrier.rs"]
pub(crate) mod ddl_barrier;
#[path = "ddl_barrier_ack.rs"]
pub(crate) mod ddl_barrier_ack;
#[path = "ddl_barrier_ack_digest.rs"]
pub(crate) mod ddl_barrier_ack_digest;
#[path = "ddl_barrier_ack_input.rs"]
pub(crate) mod ddl_barrier_ack_input;
#[path = "ddl_barrier_ack_partition_input.rs"]
pub(crate) mod ddl_barrier_ack_partition_input;
#[path = "ddl_barrier_format.rs"]
pub(crate) mod ddl_barrier_format;
#[path = "ddl_barrier_next_actions.rs"]
pub(crate) mod ddl_barrier_next_actions;
#[path = "ddl_barrier_plan.rs"]
pub(crate) mod ddl_barrier_plan;
#[path = "ddl_barrier_render.rs"]
pub(crate) mod ddl_barrier_render;
#[path = "ddl_barrier_render_sections.rs"]
pub(crate) mod ddl_barrier_render_sections;
#[path = "ddl_boundary.rs"]
pub(crate) mod ddl_boundary;
#[path = "ddl_change.rs"]
pub(crate) mod ddl_change;
#[path = "ddl_change_parser.rs"]
pub(crate) mod ddl_change_parser;
#[path = "ddl_change_policy.rs"]
pub(crate) mod ddl_change_policy;
#[path = "ddl_envelope_barrier_plan.rs"]
pub(crate) mod ddl_envelope_barrier_plan;
#[path = "ddl_envelope_plan.rs"]
pub(crate) mod ddl_envelope_plan;
#[path = "ddl_envelope_render.rs"]
pub(crate) mod ddl_envelope_render;
#[path = "ddl_envelope_replay.rs"]
pub(crate) mod ddl_envelope_replay;
#[path = "ddl_envelope_summaries.rs"]
pub(crate) mod ddl_envelope_summaries;
#[path = "ddl_envelope_target.rs"]
pub(crate) mod ddl_envelope_target;
#[path = "ddl_labels.rs"]
pub(crate) mod ddl_labels;
#[path = "ddl_next_commands.rs"]
pub(crate) mod ddl_next_commands;
#[path = "ddl_propagation.rs"]
pub(crate) mod ddl_propagation;
#[path = "ddl_propagation_actions.rs"]
pub(crate) mod ddl_propagation_actions;
#[path = "ddl_propagation_boundary.rs"]
pub(crate) mod ddl_propagation_boundary;
#[path = "ddl_propagation_phases.rs"]
pub(crate) mod ddl_propagation_phases;
#[path = "ddl_propagation_policy.rs"]
pub(crate) mod ddl_propagation_policy;
#[path = "ddl_propagation_sinks.rs"]
pub(crate) mod ddl_propagation_sinks;
#[path = "ddl_propagation_types.rs"]
pub(crate) mod ddl_propagation_types;
#[path = "ddl_release_blockers.rs"]
pub(crate) mod ddl_release_blockers;
#[path = "ddl_release_gates.rs"]
pub(crate) mod ddl_release_gates;
#[path = "ddl_render.rs"]
pub(crate) mod ddl_render;
#[path = "ddl_sql.rs"]
pub(crate) mod ddl_sql;
#[path = "ddl_sql_type.rs"]
pub(crate) mod ddl_sql_type;
#[path = "ddl_types.rs"]
pub(crate) mod ddl_types;
