#[path = "pilot.rs"]
pub(crate) mod pilot;
#[path = "pilot_acceptance_gates.rs"]
pub(crate) mod pilot_acceptance_gates;
#[path = "pilot_evidence.rs"]
pub(crate) mod pilot_evidence;
#[path = "pilot_evidence_collection_requirements.rs"]
pub(crate) mod pilot_evidence_collection_requirements;
#[path = "pilot_evidence_contract_markers.rs"]
pub(crate) mod pilot_evidence_contract_markers;
#[path = "pilot_evidence_counts.rs"]
pub(crate) mod pilot_evidence_counts;
#[path = "pilot_evidence_ddl_markers.rs"]
pub(crate) mod pilot_evidence_ddl_markers;
#[path = "pilot_evidence_failure_markers.rs"]
pub(crate) mod pilot_evidence_failure_markers;
#[path = "pilot_evidence_gate.rs"]
pub(crate) mod pilot_evidence_gate;
#[path = "pilot_evidence_identity_helpers.rs"]
pub(crate) mod pilot_evidence_identity_helpers;
#[path = "pilot_evidence_json_path.rs"]
pub(crate) mod pilot_evidence_json_path;
#[path = "pilot_evidence_lake_markers.rs"]
pub(crate) mod pilot_evidence_lake_markers;
#[path = "pilot_evidence_lake_writer_markers.rs"]
pub(crate) mod pilot_evidence_lake_writer_markers;
#[path = "pilot_evidence_lake_writer_rows.rs"]
pub(crate) mod pilot_evidence_lake_writer_rows;
#[path = "pilot_evidence_marker_catalog.rs"]
pub(crate) mod pilot_evidence_marker_catalog;
#[path = "pilot_evidence_markers.rs"]
pub(crate) mod pilot_evidence_markers;
#[path = "pilot_evidence_partition_markers.rs"]
pub(crate) mod pilot_evidence_partition_markers;
#[path = "pilot_evidence_rebalance_markers.rs"]
pub(crate) mod pilot_evidence_rebalance_markers;
#[path = "pilot_evidence_render.rs"]
pub(crate) mod pilot_evidence_render;
#[path = "pilot_evidence_snapshot_markers.rs"]
pub(crate) mod pilot_evidence_snapshot_markers;
#[path = "pilot_evidence_source_safety_markers/mod.rs"]
pub(crate) mod pilot_evidence_source_safety_markers;
#[path = "pilot_evidence_template.rs"]
pub(crate) mod pilot_evidence_template;
#[path = "pilot_evidence_template_artifacts.rs"]
pub(crate) mod pilot_evidence_template_artifacts;
#[path = "pilot_evidence_template_files.rs"]
pub(crate) mod pilot_evidence_template_files;
#[path = "pilot_evidence_transaction_markers.rs"]
pub(crate) mod pilot_evidence_transaction_markers;
#[path = "pilot_evidence_verified_apply_markers.rs"]
pub(crate) mod pilot_evidence_verified_apply_markers;
#[path = "pilot_executive_evidence.rs"]
pub(crate) mod pilot_executive_evidence;
#[path = "pilot_executive_evidence_builder.rs"]
pub(crate) mod pilot_executive_evidence_builder;
#[path = "pilot_executive_evidence_render.rs"]
pub(crate) mod pilot_executive_evidence_render;
#[path = "pilot_guide_sections.rs"]
pub(crate) mod pilot_guide_sections;
#[path = "pilot_package.rs"]
pub(crate) mod pilot_package;
#[path = "pilot_package_artifact_list.rs"]
pub(crate) mod pilot_package_artifact_list;
#[path = "pilot_package_artifact_sections.rs"]
pub(crate) mod pilot_package_artifact_sections;
#[path = "pilot_package_artifacts.rs"]
pub(crate) mod pilot_package_artifacts;
#[path = "pilot_package_ddl_envelope.rs"]
pub(crate) mod pilot_package_ddl_envelope;
#[path = "pilot_package_ddl_release.rs"]
pub(crate) mod pilot_package_ddl_release;
#[path = "pilot_package_ddl_release_ack_samples.rs"]
pub(crate) mod pilot_package_ddl_release_ack_samples;
#[path = "pilot_package_ddl_release_acks.rs"]
pub(crate) mod pilot_package_ddl_release_acks;
#[path = "pilot_package_ddl_release_sink_acks.rs"]
pub(crate) mod pilot_package_ddl_release_sink_acks;
#[path = "pilot_package_ddl_status.rs"]
pub(crate) mod pilot_package_ddl_status;
#[path = "pilot_package_feature_pull.rs"]
pub(crate) mod pilot_package_feature_pull;
#[path = "pilot_package_first_commands.rs"]
pub(crate) mod pilot_package_first_commands;
#[path = "pilot_package_handoff_artifacts.rs"]
pub(crate) mod pilot_package_handoff_artifacts;
#[path = "pilot_package_lake_completeness.rs"]
pub(crate) mod pilot_package_lake_completeness;
#[path = "pilot_package_lake_sample.rs"]
pub(crate) mod pilot_package_lake_sample;
#[path = "pilot_package_materials.rs"]
pub(crate) mod pilot_package_materials;
#[path = "pilot_package_materials_lake.rs"]
pub(crate) mod pilot_package_materials_lake;
#[path = "pilot_package_next.rs"]
pub(crate) mod pilot_package_next;
#[path = "pilot_package_operational_burden.rs"]
pub(crate) mod pilot_package_operational_burden;
#[path = "pilot_package_partner.rs"]
pub(crate) mod pilot_package_partner;
#[path = "pilot_package_platform_artifacts.rs"]
pub(crate) mod pilot_package_platform_artifacts;
#[path = "pilot_package_platform_diagnostics_artifacts.rs"]
pub(crate) mod pilot_package_platform_diagnostics_artifacts;
#[path = "pilot_package_platform_fleet_artifacts.rs"]
pub(crate) mod pilot_package_platform_fleet_artifacts;
#[path = "pilot_package_platform_lake_artifacts.rs"]
pub(crate) mod pilot_package_platform_lake_artifacts;
#[path = "pilot_package_platform_spark_artifacts.rs"]
pub(crate) mod pilot_package_platform_spark_artifacts;
#[path = "pilot_package_proof_bundle.rs"]
pub(crate) mod pilot_package_proof_bundle;
#[path = "pilot_package_readme.rs"]
pub(crate) mod pilot_package_readme;
#[path = "pilot_package_readme_artifacts.rs"]
pub(crate) mod pilot_package_readme_artifacts;
#[path = "pilot_package_readme_sections.rs"]
pub(crate) mod pilot_package_readme_sections;
#[path = "pilot_package_rebalance.rs"]
pub(crate) mod pilot_package_rebalance;
#[path = "pilot_package_source_safety.rs"]
pub(crate) mod pilot_package_source_safety;
#[path = "pilot_package_spark_golden.rs"]
pub(crate) mod pilot_package_spark_golden;
#[path = "pilot_package_spark_golden_materialize.rs"]
pub(crate) mod pilot_package_spark_golden_materialize;
#[path = "pilot_package_spark_golden_rows.rs"]
pub(crate) mod pilot_package_spark_golden_rows;
#[path = "pilot_package_support.rs"]
pub(crate) mod pilot_package_support;
#[path = "pilot_package_support_artifacts.rs"]
pub(crate) mod pilot_package_support_artifacts;
#[path = "pilot_package_writer.rs"]
pub(crate) mod pilot_package_writer;
#[path = "pilot_render.rs"]
pub(crate) mod pilot_render;
#[path = "pilot_scorecard.rs"]
pub(crate) mod pilot_scorecard;
#[path = "pilot_scorecard_commands.rs"]
pub(crate) mod pilot_scorecard_commands;
#[path = "pilot_scorecard_gates.rs"]
pub(crate) mod pilot_scorecard_gates;
#[path = "pilot_scorecard_optional_gates.rs"]
pub(crate) mod pilot_scorecard_optional_gates;
#[path = "pilot_types.rs"]
pub(crate) mod pilot_types;
