pub(crate) const PILOT_PACKAGE_ARTIFACT_LINES: &[&str] = &[
    "- `quickstart-plan.txt`: no-broker local evaluation command plan",
    "- `quickstart-readiness.txt`: readiness checks and next commands",
    "- `pilot-guide.txt`: human-readable deployment phases and acceptance gates",
    "- `pilot-guide.json`: machine-readable proof package",
    "- `pilot-scorecard.txt`: enterprise acceptance gates and proof commands",
    "- `pilot-scorecard.json`: machine-readable acceptance scorecard",
    "- `executive-evidence.md`: executive evidence brief for platform and security review",
    "- `enterprise-evaluation.txt`: buyer-facing readiness, mode-fit, and proof review path",
    "- `enterprise-evaluation.json`: machine-readable enterprise evaluation",
    "- `schema-ddl-plan.json`: policy-gated DDL propagation plan with schema-barrier release gates and post-DDL DML visibility evidence",
    "- `schema-ddl-apply-plan.json`: dry-run target Postgres DDL apply plan with safe SQL, a reviewed transaction script, statement digests, and barrier release sequence",
    "- `schema-ddl-envelope-plan.json`: runtime DDL envelope plan with transaction barrier, event classification, propagation boundary, propagation decisions, policy digest, DML release blockers, and replay-envelope proof with `ddl_events` stripped",
    "- `ddl-barrier-status.json`: sample DDL barrier release blockers and stable `release_blocker_codes` before DML visibility",
    "- `ddl-release-proof.json`: sample DDL barrier release proof with required sink ACK evidence",
    "- `local-run-proof.md`: evidence slot for the human-readable local run proof chain",
    "- `source-safety-checklist.md`: read-only source diagnostic commands, evidence, and decision rule",
    "- `proof-bundle.md`: single-review proof chain for source safety, transaction boundaries, convergence, and recovery",
    "- `deployment-guide.md`: partner-specific deployment guide for the first flow",
    "- `operational-burden-notes.md`: before/after incident and operating burden notes",
    "- `feature-pull-list.md`: design-partner asks to validate before building Cloud",
    "- `fleet-report.txt`: fleet topology, convergence gates, recovery drills, and proof commands",
    "- `fleet-scorecard.txt`: fleet readiness verdict, go/no-go counts, blockers, and review sequence",
    "- `fleet-evidence-plan.txt`: live-evidence command sequence before fleet readiness is declared",
    "- `consistency-contract.json`: flow-level transaction visibility, checkpoint, replay, and handoff contract",
    "- `performance-envelope.json`: configuration-derived performance envelope and tuning proof commands",
    "- `identity-audit.json`: primary-key apply, replica-identity, and TOAST preservation audit",
    "- `consumer-semantics.json`: strict and partitioned consumer semantics matrix with transaction-boundary language",
    "- `lake-ddl.json`: raw CDC, epoch metadata, Spark template outputs, and checkpoint contract",
    "- `lake-epoch.json`: fleet fan-in epoch completeness decision and Spark consumption gate",
    "- `lake-verify.json`: stream-to-lake epoch reconciliation and consumption decision",
    "- `lake-completeness.json`: Iceberg completeness evidence tying epoch, verification, writer, and Spark gates together",
    "- `lake-writer-plan.json`: raw CDC append-file and epoch-metadata writer intent for a verified sample envelope",
    "- `sample-envelope.pb`: deterministic transaction envelope used by package lake writer and fan-in commands",
    "- `lake-fanin-run.json`: bounded local fan-in dry-run verdict with replay and Spark release gates",
    "- `spark-current-state.sql`: rendered Spark SQL for deriving current-state from verified lake epochs",
    "- `spark-current-state.py`: PySpark runner for the verified current-state SQL artifact; prints `template_sha256` for Spark-derived-view DDL ACK evidence",
    "- `spark-scd2.sql`: rendered Spark SQL for deriving SCD2 history from verified lake epochs",
    "- `spark-scd2.py`: PySpark runner for the verified SCD2 SQL artifact; prints `template_sha256` for Spark-derived-view DDL ACK evidence",
    "- `spark-maintenance.sql`: rendered Spark SQL for compaction and snapshot expiry after verified lake epochs",
    "- `spark-maintenance.py`: PySpark runner for verification-gated table maintenance; prints `template_sha256` for Spark maintenance ACK review",
    "- `spark-completeness-dashboard.sql`: rendered Spark SQL for epoch and source-level completeness review",
    "- `spark-completeness-dashboard.py`: PySpark runner for the completeness dashboard SQL artifact; prints `template_sha256` for completeness-dashboard ACK review",
    "- `spark-golden-fixture.json`: deterministic raw CDC input and expected current-state/SCD2 outputs for Spark template review",
    "- `fleet-control-plane.json`: conservative hosted control-plane pull report grounded in local fleet evidence",
    "- `diagnostics.txt`: support-ready diagnostics bundle for escalation",
    "- `diagnostics.json`: machine-readable diagnostics bundle",
    "- `correctness-report.html`: static deterministic correctness report for failure-matrix and replay-boundary review",
    "- `live-evidence/README.md`: operator handoff for collecting live scorecard evidence",
    "- `live-evidence/collect.sh`: reviewable shell script that writes gate evidence artifacts",
    "- `manifest.json`: artifact byte counts and SHA-256 digests",
];

pub(crate) const EVIDENCE_REGISTRY_INSTRUCTION: &str =
    "Run `trellara evidence-registry --package <this-directory> --format text` after generation to verify every manifest digest and package the evidence review index.";
