pub(crate) const MAKEFILE_MARKERS: &[&str] = &[
    "local-run-proof.md",
    "Trellara Local Run Proof",
    "snapshot_handoff_blocker_codes",
    "snapshot_handoff_recovery_actions",
    "barrier_pending_blockers",
    "barrier_pending_blocker_codes",
    "barrier_pending_recovery_actions",
    "enterprise-evaluation.txt",
    "quickstart-readiness.txt",
    "trellara check --config $(QUICKSTART_CONFIG) --format text",
    "deployment-guide.md",
    "operational-burden-notes.md",
    "feature-pull-list.md",
    "source-safety-checklist.md",
    "fleet-report.txt",
    "fleet-scorecard.txt",
    "fleet-control-plane.json",
    "read_only_fleet_topology",
    "deployment_orchestration",
    "diagnostics.txt",
    "diagnostics.json",
    "consistency-contract.json",
    "source_ack_contract",
    "snapshot_handoff_contract",
    "target_checkpoint_contract",
    "performance-envelope.json",
    "stream_spill_threshold_changes",
    "transaction_boundary_cost",
    "measurement_note",
    "identity-audit.json",
    "schema-ddl-plan.json",
    "schema-ddl-apply-plan.json",
    "schema-ddl-envelope-plan.json",
    "ddl-barrier-status.json",
    "schema_ddl_plan",
    "schema_ddl_apply_plan",
    "schema_ddl_envelope_plan",
    "ddl-release-proof.json",
    "cdc_transaction_boundary",
    "ack_evidence",
    "release_gates",
    "post_ddl_dml_release",
    "release_blocker_codes",
    "release_decision",
    "blocker_codes",
    "rejection_code",
    "trellara schema ddl-plan --config",
    "trellara schema ddl-barrier record --config",
    "trellara schema ddl-barrier ack --config",
    "trellara schema ddl-barrier status --config",
    "ordinary_pk_tables_do_not_require_full",
    "plans_delete_with_key_predicate",
    "update_omits_absent_non_key_columns_for_unchanged_toast",
    "update_omits_explicit_unchanged_toast_marker",
    "evidence-registry.txt",
    "verified_artifacts: 50",
    "review_surfaces:",
    "16 required, 0 missing_required",
    "correctness-report.html",
    "package/correctness-report.html",
    "Trellara correctness report",
    "package_manifest_sha256",
    "fleet-identity-audit.txt",
    "blocked_by_identity_collision",
    "assign unique source.id and dataset.id values",
    "fleet-evidence-plan.txt",
    "ready_to_collect_live_evidence",
    "required_live_artifacts:",
    "transaction_boundary",
    "transaction-boundary.txt",
    "trellara partition-watermarks --config",
    "live-evidence/README.md",
    "live-evidence/collect.sh",
    "ddl_release_proof",
    "release_dml true",
    "propagation_boundary",
    "propagation_decisions",
    "propagation_policy_sha256",
    "ack_commands",
    "trellara pilot evidence-template --config",
    "trellara pilot evidence-check --config",
    "consumer-semantics.json",
    "exact_transaction",
    "partition_local",
    "lake-ddl.json",
    "lake-epoch.json",
    "lake-verify.json",
    "lake-completeness.json",
    "lake-writer-plan.json",
    "sample-envelope.pb",
    "lake-fanin-run.json",
    "recovery_guidance",
    "explicit_gap_acceptance_required",
    "operator_action",
    "source acknowledgement advances after durable Trellara stream publish",
    "source WAL remains protected",
    "before source acknowledgement",
    "trellara lake writer-plan --config",
    "trellara lake epoch --config",
    "trellara lake fanin verify --config",
    "--accept-complete-with-gaps",
    "retail_sales__public__sales__raw_cdc",
    "_trellara_epochs",
    "_trellara_epoch_sources",
    "_trellara_verification",
    "retail_sales__spark__derived__current_state",
    "retail_sales__spark__derived__scd2_history",
    "spark-current-state.sql",
    "spark-current-state.py",
    "spark-scd2.sql",
    "spark-scd2.py",
    "spark-maintenance.sql",
    "spark-maintenance.py",
    "spark-completeness-dashboard.sql",
    "spark-completeness-dashboard.py",
    "spark-golden-fixture.json",
    "trellara lake spark-template current-state --config",
    "trellara lake spark-template scd2 --config",
    "trellara lake spark-template maintenance --config",
    "Trellara Source Safety Checklist",
    "Trellara fleet report",
    "Trellara fleet scorecard",
];

pub(crate) const MAKEFILE_JSON_FRAGMENTS: &[&str] = &[
    "\"completeness_state\": \"complete_with_gaps\"",
    "\"verification_status\": \"match\"",
    "\"spark_consumption_gate\": \"released: stream and lake proofs match, complete_with_gaps was explicitly accepted, and verification_status=match\"",
    "\"committer_topology\"",
    "\"strategy\": \"single_table_committer_epoch_batched_append_only_raw_cdc\"",
    "\"commit_steps\"",
    "\"phase\": \"raw_cdc_data\"",
    "\"phase\": \"epoch_row_metadata\"",
    "\"phase\": \"verification_metadata\"",
    "\"recovery_scenarios\"",
    "\"code\": \"writer_crash_after_epoch_metadata\"",
    "\"replay_policy\": \"discover_existing_epoch_metadata_before_publish\"",
    "\"code\": \"verification_mismatch_after_commit\"",
    "\"replay_policy\": \"hold_spark_consumption_until_fanin_verify_matches\"",
];
