use super::*;

impl PilotPackageContents {
    pub(super) fn assert_lake_contents(&self) {
        assert_content_contains(
            "lake DDL",
            &self.lake_ddl,
            &[
                "\"table_count\": 7",
                "\"checkpoint_contract\"",
                "retail_sales__public__sales__raw_cdc",
                "_trellara_epochs",
                "_trellara_epoch_sources",
                "_trellara_epoch_partitions",
                "_trellara_verification",
                "retail_sales__spark__derived__current_state",
                "retail_sales__spark__derived__scd2_history",
                "__trellara_commit_lsn",
                "__trellara_epoch_id",
            ],
        );
        assert_content_contains(
            "lake epoch",
            &self.lake_epoch,
            &[
                "\"state\": \"complete_with_gaps\"",
                "\"customer_decision\": \"requires_explicit_gap_acceptance_before_spark_consumption\"",
                "\"missing_source_count\": 3",
            ],
        );
        assert_content_contains(
            "lake verify",
            &self.lake_verify,
            &[
                "\"status\": \"match\"",
                "\"spark_consumption_allowed\": true",
                "\"mismatch_count\": 0",
                "\"warning_mismatch_count\": 0",
                "\"blocker_mismatch_count\": 0",
                "\"contract\": \"fleet_fanin_append_only_raw_cdc_with_epoch_completeness\"",
            ],
        );
        assert_content_contains(
            "lake completeness",
            &self.lake_completeness,
            &[
                "\"contract\": \"fleet_fanin_append_only_raw_cdc_with_epoch_completeness\"",
                "\"completeness_state\": \"complete_with_gaps\"",
                "\"verification_status\": \"match\"",
                "\"spark_consumption_allowed\": true",
                "\"source_counts_match\": true",
                "\"stream_required_source_count\": 12",
                "\"lake_required_source_count\": 12",
                "\"checksum_rollup_match\": true",
                "\"stream_checksum_rollup\"",
                "\"lake_checksum_rollup\"",
                "\"spark_consumption_contract\": \"lake_epoch_consumption_requires_matching_verified_metadata_and_explicit_gap_acceptance\"",
                "\"spark_consumption_gate\": \"released: stream and lake proofs match, complete_with_gaps was explicitly accepted, and verification_status=match\"",
                "\"source_watermark_count\": 12",
                "\"partition_rollup_count\": 9",
                "\"partition_skew\"",
                "\"participating_partition_count\": 8",
                "\"total_event_count\": 9",
                "\"skew_ratio_basis_points\": 20000",
                "\"hottest_partition_ids\"",
                "\"coolest_partition_ids\"",
                "\"source_rows\"",
                "\"source_id\": \"local-source\"",
                "\"state\": \"complete\"",
                "\"start_lsn\": \"0/16B6C50\"",
                "\"end_lsn\": \"0/16B6C50\"",
                "\"lag_reason\": null",
                "\"committer_strategy\": \"single_table_committer_epoch_batched_append_only_raw_cdc\"",
                "source acknowledgement advances after durable Trellara stream publish",
                "source WAL remains protected",
                "\"writer_crash_after_epoch_metadata\"",
                "\"verification_mismatch_after_commit\"",
                "\"recovery_guidance\"",
                "\"code\": \"explicit_gap_acceptance_required\"",
                "\"consumer_gate\": \"blocked unless the consumer explicitly accepts recorded gaps\"",
                "record customer acceptance for the listed missing, lagging, or quarantined sources",
                "\"evidence_required\": \"gap list in _trellara_epoch_sources and --accept-complete-with-gaps in verification evidence\"",
                "\"artifact\": \"spark-current-state.sql\"",
                "\"gate\": \"released: stream and lake proofs match, complete_with_gaps was explicitly accepted, and verification_status=match\"",
                "\"artifact\": \"spark-completeness-dashboard.sql\"",
                "lake-fanin-run.json",
                "\"decision_rule\": \"Spark jobs may consume only verified complete epochs",
            ],
        );
        assert_content_contains(
            "lake writer plan",
            &self.lake_writer_plan,
            &[
                "\"duplicate_transaction_count\": 1",
                "\"data_file_count\": 1",
                "\"committer_topology\"",
                "\"strategy\": \"single_table_committer_epoch_batched_append_only_raw_cdc\"",
                "\"source_ack_boundary\": \"source acknowledgement advances after durable Trellara stream publish, not after Iceberg catalog commit\"",
                "\"catalog_backpressure_rule\": \"slow Iceberg catalog commits backpressure lake fan-in consumers while source WAL remains protected by the durable stream boundary\"",
                "\"commit_steps\"",
                "\"phase\": \"raw_cdc_data\"",
                "\"phase\": \"epoch_row_metadata\"",
                "\"phase\": \"verification_metadata\"",
                "Iceberg checkpoint receipts",
                "\"source_rows\"",
                "\"partition_rows\"",
                "\"recovery_scenarios\"",
                "\"code\": \"writer_crash_after_epoch_metadata\"",
                "\"replay_policy\": \"discover_existing_epoch_metadata_before_publish\"",
                "\"code\": \"verification_mismatch_after_commit\"",
                "\"replay_policy\": \"hold_spark_consumption_until_fanin_verify_matches\"",
                "before source acknowledgement",
                "verify checkpoint receipts",
                "discover epoch epoch-retail-sales-",
                "retail_sales__public__sales__raw_cdc",
                "epoch_id=epoch-retail-sales-",
                "\"row_intents\"",
                "\"source_id\": \"local-source\"",
                "\"relation\": \"public.sales\"",
                "\"operation\": \"insert\"",
                "\"transaction_id\": \"tx-lake-writer-sample\"",
                "\"record_key\": \"sample-1\"",
                "\"idempotency_key\": \"local-source:0/16B6C50:tx-lake-writer-sample:2\"",
                "\"schema_fingerprint\": null",
                "\"schema_version\": 67890",
                "\"ddl_barrier_id\": \"local-source:retail-sales:tx-lake-writer-sample:0/16B6C50:ddl\"",
                "\"ddl_release_gate\": \"post_ddl_dml_release\"",
                "\"ddl_schema_fingerprint_before\": 12345",
                "\"ddl_schema_fingerprint_after\": 67890",
                "\"payload_after\"",
                "\"envelope_checksum\"",
            ],
        );
        assert_content_contains(
            "lake fan-in run",
            &self.lake_fanin_run,
            &[
                "\"trial_status\": \"planned_with_duplicate_replays\"",
                "\"duplicate_replay_count\": 1",
                "\"data_file_count\": 1",
                "\"replay_safe\": true",
                "\"spark_release_gate\": \"publish Spark jobs only after trellara lake fanin verify reports match for this epoch\"",
                "\"source_ack_boundary\": \"source acknowledgement advances after durable Trellara stream publish, not after Iceberg catalog commit\"",
                "\"bounded_trial_note\": \"dry-run local trial: no Iceberg catalog writes are performed",
                "\"writer_plan\"",
                "\"verification_row\"",
            ],
        );
    }
}
