use super::*;

impl PilotPackageContents {
    pub(super) fn assert_manifest(&self) {
        assert_content_contains(
            "manifest",
            &self.manifest,
            &[
                "\"artifact_count\": 50",
                "\"sha256\"",
                "pilot-scorecard.json",
                "executive-evidence.md",
                "enterprise-evaluation.txt",
                "enterprise-evaluation.json",
                "schema-ddl-plan.json",
                "schema-ddl-apply-plan.json",
                "schema-ddl-envelope-plan.json",
                "ddl-barrier-status.json",
                "ddl-release-proof.json",
                "local-run-proof.md",
                "source-safety-checklist.md",
                "proof-bundle.md",
                "deployment-guide.md",
                "operational-burden-notes.md",
                "feature-pull-list.md",
                "fleet-report.txt",
                "fleet-scorecard.txt",
                "fleet-evidence-plan.txt",
                "consistency-contract.json",
                "performance-envelope.json",
                "identity-audit.json",
                "consumer-semantics.json",
                "lake-ddl.json",
                "lake-epoch.json",
                "lake-verify.json",
                "lake-completeness.json",
                "lake-writer-plan.json",
                "sample-envelope.pb",
                "lake-fanin-run.json",
                "spark-current-state.sql",
                "spark-current-state.py",
                "spark-scd2.sql",
                "spark-scd2.py",
                "spark-maintenance.sql",
                "spark-maintenance.py",
                "spark-completeness-dashboard.sql",
                "spark-completeness-dashboard.py",
                "spark-golden-fixture.json",
                "fleet-control-plane.json",
                "diagnostics.txt",
                "diagnostics.json",
                "correctness-report.html",
                "live-evidence/README.md",
                "live-evidence/collect.sh",
            ],
        );
    }
}
