use super::*;

pub(super) fn assert_ddl_proofs(contents: &PilotPackageContents) {
    assert_content_contains(
        "schema DDL plan",
        &contents.schema_ddl_plan,
        &[
            "\"verdict\": \"ready_to_apply\"",
            "\"decision\": \"auto_apply\"",
            "\"transaction_boundary_rule\"",
            "\"release_gates\"",
            "\"schema_barrier_recorded\"",
            "\"post_ddl_dml_release\"",
            "release_blockers",
            "schema barrier",
        ],
    );
    assert_content_contains(
        "schema DDL apply plan",
        &contents.schema_ddl_apply_plan,
        &[
            "\"executable\": true",
            "\"plan_sha256\"",
            "\"transaction_boundary_rule\"",
            "\"statement_count\": 1",
            "\"statement_sha256\"",
            "\"target_postgres\"",
            "\"target_postgres_transaction_script\"",
            "\"target_postgres_ack_commands\"",
            "\"transaction_scope\"",
            "\"release_gate_code\": \"post_ddl_dml_release\"",
            "--sink target_postgres",
            "ALTER TABLE",
            "BEGIN;",
            "COMMIT;",
            "Do not record target_postgres ACK",
            "post_ddl_dml_release",
            "schema ddl-barrier record",
        ],
    );
    assert_content_contains(
        "schema DDL envelope plan",
        &contents.schema_ddl_envelope_plan,
        &[
            "\"ddl_event_count\": 1",
            "\"operation\": \"add_column\"",
            "\"target_auto_apply\": true",
            "\"executable\": true",
            "\"required_sinks\"",
            "\"target_sql\"",
            "\"propagation_boundary\": \"source_commit_lsn_barrier_holds_post_ddl_dml_until_required_sink_acks\"",
            "\"propagation_decisions\"",
            "\"auto_apply:1\"",
            "\"target_ack_required:1\"",
            "\"propagation_policy_sha256\"",
            "post_ddl_dml_release",
        ],
    );
    assert_content_contains(
        "DDL barrier status",
        &contents.ddl_barrier_status,
        &[
            "\"release_dml\": false",
            "\"release_blockers\"",
            "\"release_blocker_codes\"",
            "\"release_blocker_details\"",
            "\"rejection_code\"",
            "\"release_gates\"",
            "\"post_ddl_dml_release\"",
            "\"propagation_boundary\": \"source_commit_lsn_barrier_holds_post_ddl_dml_until_required_sink_acks\"",
            "\"propagation_decisions\"",
            "\"propagation_policy_sha256\"",
            "pending required sink acknowledgements",
            "\"raw_cdc_lake\"",
            "\"spark_derived_views\"",
        ],
    );
    assert_content_contains(
        "DDL release proof",
        &contents.ddl_release_proof,
        &[
            "\"release_gate\": \"post_ddl_dml_release\"",
            "\"cdc_transaction_boundary\"",
            "source commit LSN is the DDL barrier",
            "\"required_sinks\"",
            "\"ack_commands\"",
            "trellara schema ddl-barrier ack --config trellara.yml",
            "--plan-sha256",
            "--statement-sha256",
            "--sink raw_cdc_lake",
            "--metadata-table retail_sales__trellara__fanin___trellara_epoch_sources",
            "--partition-metadata-table retail_sales__trellara__fanin___trellara_epoch_partitions",
            "\"sink\": \"raw_cdc_lake\"",
            "raw CDC lake recorded schema_version schema-v2",
            "partition_metadata_table=retail_sales__trellara__fanin___trellara_epoch_partitions",
            "manifest_digest=abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
            "\"sink\": \"spark_derived_views\"",
            "Spark-derived views accepted 4 regenerated templates",
            "template_digest=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
            "accepted_by=pilot-package-generator",
            "\"sink\": \"target_postgres\"",
            "target Postgres applied 1 DDL statements",
            "plan_sha256",
            "statement_sha256",
            "\"release_evidence\"",
            "required sink ACKs accepted",
            "post-DDL DML release_dml=true",
            "\"release_summary\"",
            "\"release_decision\"",
            "\"blocker_codes\"",
            "\"blocker_details\"",
            "\"propagation_boundary\": \"source_commit_lsn_barrier_holds_post_ddl_dml_until_required_sink_acks\"",
            "\"propagation_decisions\"",
            "\"propagation_policy_sha256\"",
            "\"release_dml\": true",
            "\"pending_sink_count\": 0",
            "\"post_ddl_dml_release\"",
        ],
    );
}
