use super::*;

pub(super) fn assert_readme_inventory(contents: &PilotPackageContents) {
    assert_content_contains(
        "README",
        &contents.readme,
        &[
            "Trellara Pilot Package",
            "executive-evidence.md",
            "enterprise-evaluation.txt",
            "enterprise-evaluation.json",
            "schema-ddl-plan.json",
            "schema-ddl-apply-plan.json",
            "schema-ddl-envelope-plan.json",
            "dry-run target Postgres DDL apply plan",
            "runtime DDL envelope plan",
            "propagation boundary",
            "propagation decisions",
            "policy digest",
            "replay-envelope proof with `ddl_events` stripped",
            "schema-barrier release gates",
            "release_blocker_codes",
            "post-DDL DML visibility evidence",
            "ddl-barrier-status.json",
            "local-run-proof.md",
            "source-safety-checklist.md",
            "proof-bundle.md",
            "deployment-guide.md",
            "operational-burden-notes.md",
            "feature-pull-list.md",
            "fleet-report.txt",
            "fleet-scorecard.txt",
            "fleet-evidence-plan.txt",
            "consistency-contract.json",
            "performance-envelope.json",
            "identity-audit.json",
            "consumer-semantics.json",
            "lake-ddl.json",
            "lake-epoch.json",
            "lake-verify.json",
            "lake-completeness.json",
            "lake-writer-plan.json",
            "lake-fanin-run.json",
            "spark-current-state.sql",
            "spark-current-state.py",
            "PySpark runner for the verified current-state SQL artifact; prints `template_sha256` for Spark-derived-view DDL ACK evidence",
            "spark-scd2.sql",
            "spark-scd2.py",
            "PySpark runner for the verified SCD2 SQL artifact; prints `template_sha256` for Spark-derived-view DDL ACK evidence",
            "spark-maintenance.sql",
            "spark-maintenance.py",
            "PySpark runner for verification-gated table maintenance; prints `template_sha256` for Spark maintenance ACK review",
            "spark-completeness-dashboard.sql",
            "spark-completeness-dashboard.py",
            "PySpark runner for the completeness dashboard SQL artifact; prints `template_sha256` for completeness-dashboard ACK review",
            "spark-golden-fixture.json",
            "fleet-control-plane.json",
            "diagnostics.txt",
            "diagnostics.json",
            "live-evidence/README.md",
            "live-evidence/collect.sh",
            "trellara evaluate --config",
            "trellara schema ddl-plan --config",
            "trellara lake writer-plan --config",
            "trellara lake spark-template dashboard --config",
            "trellara pilot-evidence --config",
            "trellara pilot evidence-template --config",
            "trellara pilot evidence-check --config",
            "trellara check --config",
            "trellara fleet report --config",
            "trellara fleet scorecard --config",
            "trellara fleet evidence-plan --config",
            "trellara consistency --config",
            "trellara performance --config",
            "trellara identity-audit --config",
            "trellara semantics --config",
            "trellara lake ddl --config",
            "trellara lake epoch --config",
            "trellara lake fanin verify --config",
            "trellara lake spark-template current-state --config",
            "trellara lake spark-template scd2 --config",
            "trellara lake spark-template maintenance --config",
            "trellara fleet control-plane --config",
            "trellara evidence-registry --package",
        ],
    );
}
