use super::*;

#[test]
fn target_ddl_transaction_plan_accepts_safe_additive_sql() {
    let plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");

    assert_eq!(plan.barrier_id, "ddl-barrier-123");
    assert_eq!(plan.statement_count, 1);
    assert_eq!(plan.release_gate, "post_ddl_dml_release");
    assert_eq!(plan.plan_sha256.len(), 64);
    assert_eq!(plan.statement_sha256s.len(), 1);
    assert_eq!(plan.statement_sha256s[0].len(), 64);
    assert_eq!(plan.statements[0].operation, "ddl");
    assert_eq!(plan.statements[0].total_order, 1);
    assert_eq!(
        plan.statements[0].sql,
        "ALTER TABLE \"public\".\"sales\" ADD COLUMN IF NOT EXISTS \"discount_code\" text;"
    );
    assert!(plan.statements[0].values.is_empty());
    assert!(!plan.statements[0].requires_row_match);
    assert!(plan
        .steps
        .iter()
        .any(|step| step.contains("target schema transaction")));
    validate_ddl_transaction_plan(&plan).expect("executable plan validates");
}

#[test]
fn target_ddl_transaction_plan_accepts_retry_safe_additive_sql() {
    let mut input = safe_plan();
    input.statements[0].sql =
        "ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS discount_code text;".to_string();

    let plan = plan_target_ddl_transaction(input).expect("retry-safe ddl transaction plan");

    assert_eq!(
        plan.statements[0].sql,
        "ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS discount_code text;"
    );
}

#[test]
fn target_ddl_transaction_plan_refuses_blockers() {
    let mut input = safe_plan();
    input.blockers.push("manual review required".to_string());

    assert!(matches!(
        plan_target_ddl_transaction(input),
        Err(ApplyError::DdlApplyBlocked { barrier_id, blockers })
            if barrier_id == "ddl-barrier-123" && blockers == vec!["manual review required"]
    ));
}

#[test]
fn target_ddl_transaction_plan_requires_barrier_id() {
    let mut input = safe_plan();
    input.barrier_id = " ".to_string();

    assert!(matches!(
        plan_target_ddl_transaction(input),
        Err(ApplyError::MissingDdlField {
            field: "barrier_id"
        })
    ));
}

#[test]
fn target_ddl_transaction_plan_rejects_padded_barrier_id() {
    let mut input = safe_plan();
    input.barrier_id = "ddl-barrier-123 ".to_string();

    assert!(matches!(
        plan_target_ddl_transaction(input),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "barrier_id" && reason == "must not contain surrounding whitespace"
    ));
}

#[test]
fn target_ddl_transaction_plan_requires_release_gate() {
    let mut input = safe_plan();
    input.release_gate = "target_only".to_string();

    assert!(matches!(
        plan_target_ddl_transaction(input),
        Err(ApplyError::MissingDdlField {
            field: "post_ddl_dml_release"
        })
    ));
}

#[test]
fn target_ddl_transaction_plan_requires_statements() {
    let mut input = safe_plan();
    input.statements.clear();

    assert!(matches!(
        plan_target_ddl_transaction(input),
        Err(ApplyError::MissingDdlField {
            field: "statements"
        })
    ));
}

#[test]
fn target_ddl_transaction_plan_rejects_unsafe_sql() {
    for sql in [
        "DROP TABLE public.sales;",
        "ALTER TABLE public.sales DROP COLUMN discount_code;",
        "ALTER TABLE public.sales RENAME COLUMN a TO b;",
        "ALTER TABLE public.sales ADD COLUMN code text NOT NULL;",
        "ALTER TABLE public.sales ADD COLUMN code text NOT\nNULL;",
        "ALTER TABLE public.sales ADD COLUMN code text DEFAULT 'new';",
        "ALTER TABLE public.sales ADD COLUMN code text\tDEFAULT('new');",
        "ALTER TABLE public.sales ADD COLUMN code text UNIQUE;",
        "ALTER TABLE public.sales ADD COLUMN account_id bigint REFERENCES public.accounts(id);",
        "ALTER TABLE public.sales ADD COLUMN quantity int CHECK (quantity > 0);",
        "ALTER TABLE public.sales ADD COLUMN normalized text GENERATED ALWAYS AS (lower(code)) STORED;",
        "ALTER TABLE public.sales ADD COLUMN row_id bigint GENERATED BY DEFAULT AS IDENTITY;",
        "ALTER TABLE public.sales ADD COLUMN code text CONSTRAINT code_not_empty CHECK (code <> '');",
        "ALTER TABLE public.sales ADD COLUMN code text PRIMARY KEY;",
        "ALTER TABLE public.sales ADD COLUMN code text; DROP TABLE public.sales;",
        "ALTER TABLE public.sales ADD COLUMN code text; -- comment",
    ] {
        let mut input = safe_plan();
        input.statements[0].sql = sql.to_string();

        assert!(matches!(
            plan_target_ddl_transaction(input),
            Err(ApplyError::UnsafeDdlStatement { .. })
        ));
    }
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_tampered_statement_count() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statement_count = 2;

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement_count" && reason == "expected 1, got 2"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_non_contiguous_statement_order() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statements[0].total_order = 7;

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement.total_order" && reason == "expected 1, got 7"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_non_ddl_statement() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statements[0].operation = "insert";

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement.operation" && reason == "must be ddl"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_bound_values() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statements[0].values.push(SqlValue {
        column: "discount_code".to_string(),
        value: SqlValueData::Text("promo".to_string()),
    });

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement.values" && reason == "DDL statements must not carry bind values"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_row_match_requirement() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statements[0].requires_row_match = true;

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement.requires_row_match"
                && reason == "DDL statements must not require row matches"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_tampered_unsafe_sql() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statements[0].sql = "DROP TABLE public.sales;".to_string();

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::UnsafeDdlStatement { change, reason })
            if change == "executable target DDL statement"
                && reason == "only additive ALTER TABLE ADD COLUMN is auto-applied"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_tampered_digest() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.plan_sha256 = "a".repeat(64);

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "plan_sha256"
                && reason == "must match the validated target DDL transaction plan"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_missing_statement_digest() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statement_sha256s.clear();

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement_sha256" && reason == "expected 1 statement digests"
    ));
}

#[test]
fn target_ddl_transaction_plan_validation_rejects_tampered_statement_digest() {
    let mut plan = plan_target_ddl_transaction(safe_plan()).expect("ddl transaction plan");
    plan.statement_sha256s[0] = "a".repeat(64);

    assert!(matches!(
        validate_ddl_transaction_plan(&plan),
        Err(ApplyError::InvalidDdlField { field, reason })
            if field == "statement_sha256"
                && reason == "must match the validated target DDL statement SQL"
    ));
}
