use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct LakeRawCdcRowIntent {
    pub source_id: String,
    pub source_bucket: u32,
    pub database_id: String,
    pub dataset_id: String,
    pub relation: String,
    pub transaction_id: String,
    pub begin_lsn: String,
    pub commit_lsn: String,
    pub commit_timestamp_ms: i64,
    pub total_order: u32,
    pub operation: String,
    pub record_key: Option<String>,
    pub idempotency_key: String,
    pub schema_fingerprint: Option<u64>,
    pub schema_version: Option<u64>,
    pub ddl_barrier_id: Option<String>,
    pub ddl_release_gate: Option<String>,
    pub ddl_schema_fingerprint_before: Option<u64>,
    pub ddl_schema_fingerprint_after: Option<u64>,
    pub envelope_checksum: u64,
    pub manifest_id: Option<String>,
    pub manifest_boundary_mode: Option<String>,
    pub manifest_global_event_count: Option<u32>,
    pub manifest_participating_partition_count: Option<u32>,
    pub partition_key: Option<String>,
    pub epoch_id: String,
    pub ingested_at: String,
    pub payload_before: Vec<crate::LakeColumnValue>,
    pub payload_after: Vec<crate::LakeColumnValue>,
}
