use std::fs;
use std::path::Path;

pub(super) fn is_current(repository_root: &Path) -> bool {
    fs::read_to_string(repository_root.join("Makefile")).is_ok_and(|makefile| {
        makefile.contains("schema-ddl-plan.json")
            && makefile.contains("schema-ddl-apply-plan.json")
            && makefile.contains("schema-ddl-envelope-plan.json")
            && makefile.contains("ddl-barrier-status.json")
            && makefile.contains("ddl-release-proof.json")
            && makefile.contains("partitioned-schema-ddl-plan.json")
            && makefile.contains("blocked-schema-ddl-plan.json")
            && has_json_marker(&makefile, "propagation")
            && has_json_marker(&makefile, "dml_after_barrier_held")
            && has_json_bool(&makefile, "dml_after_barrier_held", true)
            && has_json_marker(&makefile, "release_gates")
            && has_json_marker(&makefile, "post_ddl_dml_release")
            && has_json_marker(&makefile, "requires_global_partition_pause")
            && has_json_bool(&makefile, "requires_global_partition_pause", false)
            && has_json_bool(&makefile, "requires_global_partition_pause", true)
            && makefile.contains("target_postgres")
            && makefile.contains("raw_cdc_lake")
            && makefile.contains("spark_derived_view")
            && makefile.contains("partition_visibility")
            && makefile.contains("partitioned: all partition lanes")
            && makefile.contains("partition-watermarks output showing every partition")
            && has_json_marker(&makefile, "required_ack")
            && has_json_marker(&makefile, "cdc_transaction_boundary")
            && has_json_marker(&makefile, "ack_commands")
            && has_json_marker(&makefile, "ack_evidence")
            && has_json_marker(&makefile, "release_dml")
            && has_json_marker(&makefile, "release_blockers")
            && has_json_marker(&makefile, "blockers")
            && has_json_marker(&makefile, "release_blocker_codes")
            && has_json_marker(&makefile, "rejection_code")
            && has_json_marker(&makefile, "release_decision")
            && has_json_marker(&makefile, "blocker_codes")
            && has_json_marker(&makefile, "release_impact")
            && makefile.contains("change_partition_key:public.sales.region_id")
            && makefile.contains("partition-key changes alter partitioned scale mode ordering")
            && makefile.contains("pending required sink acknowledgements")
            && makefile.contains("partition_visibility_watermark")
            && has_json_marker(&makefile, "target_postgres_sql")
            && makefile.contains("schema_ddl_envelope_plan")
            && has_json_marker(&makefile, "ddl_event_count")
            && has_json_marker(&makefile, "executable")
            && has_json_marker(&makefile, "statement_count")
            && has_json_marker(&makefile, "propagation_boundary")
            && makefile
                .contains("source_commit_lsn_barrier_holds_post_ddl_dml_until_required_sink_acks")
            && has_json_marker(&makefile, "propagation_decisions")
            && has_json_marker(&makefile, "propagation_policy_sha256")
            && makefile.contains("ALTER TABLE")
            && makefile.contains("trellara schema ddl-barrier record --config")
            && makefile.contains("trellara schema ddl-barrier ack --config")
            && makefile.contains("--plan-sha256 <target-ddl-plan-sha256>")
            && makefile.contains("--statement-sha256 <target-ddl-statement-sha256>")
            && makefile.contains("--epoch-id <lake-epoch-id>")
            && makefile.contains("--metadata-table <raw-cdc-epoch-metadata-table>")
            && makefile.contains("--partition-metadata-table <raw-cdc-epoch-partitions-table>")
            && makefile.contains("--manifest-digest <lake-epoch-manifest-sha256>")
            && makefile.contains("trellara lake spark-template current-state --config")
            && makefile.contains("trellara lake spark-template scd2 --config")
            && makefile.contains("--format json")
            && makefile
                .contains("--template-digest <spark-template-sha256-hex-from-template_sha256>")
            && makefile.contains("--accepted-by <reviewer-or-automation>")
            && makefile.contains("--view-count <derived-view-count>")
            && makefile.contains("--expected-partition-count <partition-count>")
            && makefile.contains("--partition-durable-lsn <partition-id>=<durable-lsn>")
            && makefile.contains("--partition-applied-lsn <partition-id>=<applied-lsn>")
            && makefile.contains("plan_sha256=")
            && makefile.contains("statement_sha256=")
            && makefile.contains("partition_metadata_table=")
            && makefile.contains("manifest_digest=")
            && makefile.contains("template_digest=")
            && makefile.contains("accepted_by=")
            && makefile.contains("trellara schema ddl-barrier status --config")
    })
}

fn has_json_marker(makefile: &str, marker: &str) -> bool {
    makefile.contains(&format!("\"{marker}\"")) || makefile.contains(&format!("\\\"{marker}\\\""))
}

fn has_json_bool(makefile: &str, marker: &str, value: bool) -> bool {
    let value = if value { "true" } else { "false" };
    makefile.contains(&format!("\"{marker}\": {value}"))
        || makefile.contains(&format!("\\\"{marker}\\\": {value}"))
}
